# inherit_from: .rubocop_todo.yml

require: # 拡張機能をロードするように設定
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  # 最新のルールを適用する
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'

### Style

# 日本語コメントを許可
Style/AsciiComments:
  Enabled: false
# クラスとモジュールのトップレベルドキュメントがなくても許可
Style/Documentation:
  Enabled: false
